name: Deploy Preview
"on": pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.restore-lerna.outputs.cache-hit != 'true'
        run: npx lerna bootstrap --scope={functions,app}

      - name: Build packages
        run: npx lerna run build --scope={functions,app} --parallel

      - name: Deploy Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ODINBOOK_30F97 }}"
          projectId: odinbook-30f97
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
